# Generated by Django 2.2 on 2019-05-04 04:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('W', (('custom', 'Personalizada'), ('template', 'Plantilla'))), ('B', 'Branding')], max_length=20)),
                ('package', models.CharField(choices=[('BAS', 'Basic'), ('PRO', 'Pro'), ('VIP', 'Vip')], max_length=3)),
                ('description', models.TextField()),
                ('payment', models.FloatField()),
                ('total_cost', models.FloatField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('delivery_date', models.CharField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
